name: Terraform Deploy en LocalStack

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: s3
        options: --health-cmd="curl -f http://localhost:4566/_localstack/health" --health-interval=5s --health-timeout=2s --health-retries=20

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan -lock=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -lock=false tfplan
